### ISSUE TITLE
Does Not Load on Macs

### ISSUE THREAD

**Issue by Renara** [majalistic/tales-of-androgyny#1]
So I tried this on my Mac (running El Capitan) but haven't had any luck; on newer versions of macOS Java needs to be downloaded from Oracle, but their version no longer seems to include the JAR Launcher (so no double clicking), so I launched instead using:

```
java -jar TrapRPG.jar
```

Which shows the main menu just fine, and makes sounds from selecting an option but I can't get anywhere from there; clicking Options or Pervert just returns me to the main menu, while clicking Begin gets to Loading 87% before crashing with the following output:

```
java[52051:6556913] 18:27:24.517 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
AL lib: (WW) FreeDevice: (0x7fd902949200) Deleting 1 Buffer(s)
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.majalis.encounter.EncounterBuilder.getTextScenes(EncounterBuilder.java:428)
    at com.majalis.encounter.EncounterBuilder.getClassChoiceEncounter(EncounterBuilder.java:70)
    at com.majalis.encounter.EncounterFactory.getEncounter(EncounterFactory.java:36)
    at com.majalis.screens.ScreenFactoryImpl.getEncounter(ScreenFactoryImpl.java:117)
    at com.majalis.screens.ScreenFactoryImpl.getScreen(ScreenFactoryImpl.java:68)
    at com.majalis.screens.AbstractScreen.showScreen(AbstractScreen.java:42)
    at com.majalis.screens.LoadScreen.render(LoadScreen.java:43)
    at com.badlogic.gdx.Game.render(Game.java:46)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

I'm running Java SE 8 (update 101) which is the latest I can get, or is the game targeted at an older version?

Anyway, I'll give the Windows version a try in the mean-time!

**Comment by majalistic** [comment]
Hey there -

The mac version that is up should work now, hopefully.
