### ISSUE TITLE
Equipping/using weapons from inventory crashes game

### ISSUE THREAD

**Issue by meceru** [majalistic/tales-of-androgyny#4]
Bought a Rapier in Nadir, tried equipping it by clicking the item on the inventory and game crashed. Broadsword and Cutlass have the same issue too. Here's the stack trace:

`java.lang.NullPointerException
	at com.majalis.character.PlayerCharacter.consumeItem(PlayerCharacter.java:118)
	at com.majalis.screens.CharacterScreen$3.clicked(CharacterScreen.java:135)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)`

**Comment by meceru** [comment]
Nevermind, updated the game and issue is already fixed. Keep up the good work, love your writing!
